name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: &python_versions
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13-dev"
        - "pypy-3.7"
        - "pypy-3.8"
        - "pypy-3.9"
        - "pypy-3.10"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - shell: bash
      run: |
         pip install -r requirements.txt
         git submodule update --init --recursive

    - name: Build
      shell: bash
      run:  |
         python setup.py build

  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: *python_versions
          
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - shell: bash
      run: |
         pip install -r requirements.txt
         git submodule update --init --recursive

    - name: Test
      shell: bash
      run:  |
         python setup.py test

  Install:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: *python_versions
          
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - shell: bash
      run: |
         pip install -r requirements.txt
         git submodule update --init --recursive

    - name: Install
      shell: bash
      run:  |
         python setup.py install
         pypp --version
